num1=int(input("Enter the first number: "))
num2=int(input("Enter the second number: "))
print("Addition:",int(num1+num2))
print("Subtraction:",int(num1-num2))
print("Multiplication:",int(num1*num2))
print("Division:",float(num1/num2))
